<#
.SYNOPSIS
    SCCM / ConfigMgr Software Center health check and self-healing script.

.DESCRIPTION
    Performs a series of health checks against the Configuration Manager client
    and Software Center, attempting to remediate common issues automatically:
      - Service state (CcmExec, BITS, WinMgmt, wuauserv)
      - WMI repository health (root\ccm namespace)
      - Client cache integrity
      - Software Center COM/Shortcut registration
      - Stuck/failing policy state
      - Required client actions (policy retrieval/evaluation, hardware/software inventory, etc.)
      - Full client repair (ccmrepair) as a last resort

    Designed to run as SYSTEM (e.g., via SCCM Configuration Item, scheduled task,
    or Intune Win32 remediation script). Writes a CMTrace-compatible log.

.PARAMETER LogPath
    Folder where the log file is written. Default: C:\Windows\Temp

.PARAMETER MaxCacheSizeMB
    Maximum acceptable ccmcache size before purge consideration. Default: 10240 (10 GB).

.PARAMETER ForceRepair
    Forces a full ccmrepair regardless of detected health state.

.PARAMETER SkipRepair
    Detect only; do not perform repair actions. Useful for reporting / DCM detection.

.EXAMPLE
    .\Repair-SCCMSoftwareCenter.ps1

.EXAMPLE
    .\Repair-SCCMSoftwareCenter.ps1 -SkipRepair    # detection-only

.EXAMPLE
    .\Repair-SCCMSoftwareCenter.ps1 -ForceRepair

.NOTES
    Author : Generated by Claude
    Version: 1.0
    Must run elevated (SYSTEM or local admin).
    Exit code 0 = healthy / remediated, 1 = unhealthy / remediation failed.
#>

[CmdletBinding()]
param(
    [string]$LogPath = "$env:WinDir\Temp",
    [int]   $MaxCacheSizeMB = 20480,
    [switch]$ForceRepair,
    [switch]$SkipRepair
)

#region ---------- Setup ----------

$ErrorActionPreference = 'Continue'
$script:Issues   = New-Object System.Collections.Generic.List[string]
$script:Actions  = New-Object System.Collections.Generic.List[string]
$script:LogFile  = Join-Path $LogPath ("Check-SCCMHealth_{0}.log" -f (Get-Date -Format 'yyyyMMdd_HHmmss'))

if (-not (Test-Path $LogPath)) {
    New-Item -Path $LogPath -ItemType Directory -Force | Out-Null
}

function Write-Log {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Message,
        [ValidateSet('Info','Warning','Error')][string]$Severity = 'Info',
        [string]$Component = 'Check-SCCMHealth'
    )

    $sevMap = @{ 'Info' = 1; 'Warning' = 2; 'Error' = 3 }
    $time   = (Get-Date -Format 'HH:mm:ss.fff') + '+000'
    $date   = Get-Date -Format 'MM-dd-yyyy'
    $thread = [System.Threading.Thread]::CurrentThread.ManagedThreadId

    # CMTrace-compatible line
    $line = '<![LOG[{0}]LOG]!><time="{1}" date="{2}" component="{3}" context="" type="{4}" thread="{5}" file="">' -f `
            $Message, $time, $date, $Component, $sevMap[$Severity], $thread

    Add-Content -Path $script:LogFile -Value $line -Encoding UTF8

    $color = switch ($Severity) { 'Warning' {'Yellow'}; 'Error' {'Red'}; default {'Gray'} }
    Write-Host "[$Severity] $Message" -ForegroundColor $color
}

function Test-Admin {
    $id   = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $prin = New-Object System.Security.Principal.WindowsPrincipal($id)
    return $prin.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
}

#endregion

#region ---------- Detection ----------

function Test-CMClientInstalled {
    $svc = Get-Service -Name CcmExec -ErrorAction SilentlyContinue
    $path = Test-Path "$env:WinDir\CCM\CcmExec.exe"
    return ($svc -and $path)
}

function Test-RequiredServices {
    Write-Log "Checking required services..."
    $services = @(
        @{ Name = 'CcmExec' ; StartType = 'Automatic' ; Critical = $true  },
        @{ Name = 'BITS'    ; StartType = 'Automatic' ; Critical = $true  },
        @{ Name = 'Winmgmt' ; StartType = 'Automatic' ; Critical = $true  },
        @{ Name = 'wuauserv'; StartType = 'Manual'    ; Critical = $false },
        @{ Name = 'CmRcService' ; StartType = 'Automatic' ; Critical = $false }
    )

    $unhealthy = @()
    foreach ($s in $services) {
        $svc = Get-Service -Name $s.Name -ErrorAction SilentlyContinue
        if (-not $svc) {
            if ($s.Critical) {
                $unhealthy += $s.Name
                $script:Issues.Add("Service missing: $($s.Name)")
                Write-Log "Service missing: $($s.Name)" -Severity Error
            }
            continue
        }
        if ($svc.Status -ne 'Running') {
            $unhealthy += $s.Name
            $script:Issues.Add("Service not running: $($s.Name) (Status=$($svc.Status))")
            Write-Log "Service not running: $($s.Name) (Status=$($svc.Status))" -Severity Warning
        }
        if ($svc.StartType -ne $s.StartType) {
            $script:Issues.Add("Service startup wrong: $($s.Name) is $($svc.StartType), expected $($s.StartType)")
            Write-Log "Service startup wrong: $($s.Name) is $($svc.StartType), expected $($s.StartType)" -Severity Warning
        }
    }
    return $unhealthy
}

function Test-WMIHealth {
    Write-Log "Checking WMI root\ccm namespace..."
    try {
        $null = Get-CimInstance -Namespace 'root\ccm' -ClassName SMS_Client -ErrorAction Stop
        return $true
    } catch {
        $script:Issues.Add("WMI root\ccm namespace unreachable: $($_.Exception.Message)")
        Write-Log "WMI root\ccm namespace unreachable: $($_.Exception.Message)" -Severity Error
        return $false
    }
}

function Test-ClientCache {
    Write-Log "Checking client cache..."
    try {
        $cm = New-Object -ComObject 'UIResource.UIResourceMgr'
        $cache = $cm.GetCacheInfo()
        $sizeMB = [math]::Round($cache.TotalSize, 0)
        Write-Log "Cache size: ${sizeMB} MB at $($cache.Location)"
        if ($sizeMB -gt $MaxCacheSizeMB) {
            $script:Issues.Add("Cache exceeds threshold (${sizeMB} MB > ${MaxCacheSizeMB} MB)")
            return $false
        }
        return $true
    } catch {
        $script:Issues.Add("Cannot query client cache: $($_.Exception.Message)")
        Write-Log "Cannot query client cache: $($_.Exception.Message)" -Severity Warning
        return $false
    }
}

function Test-SoftwareCenterShortcut {
    Write-Log "Checking Software Center registration..."
    $exe = "$env:WinDir\CCM\ClientUX\SCClient.exe"
    if (-not (Test-Path $exe)) {
        $script:Issues.Add("SCClient.exe missing at $exe")
        Write-Log "SCClient.exe missing at $exe" -Severity Error
        return $false
    }
    # Verify AppX-style protocol handler
    $reg = 'HKLM:\SOFTWARE\Classes\softwarecenter\shell\open\command'
    if (-not (Test-Path $reg)) {
        $script:Issues.Add("softwarecenter:// protocol handler missing")
        Write-Log "softwarecenter:// protocol handler missing" -Severity Warning
        return $false
    }
    return $true
}

function Test-ClientPolicy {
    Write-Log "Checking last policy evaluation..."
    try {
        $policy = Get-CimInstance -Namespace 'root\ccm\Policy\Machine\RequestedConfig' `
                                  -ClassName CCM_Policy_Policy5 -ErrorAction Stop |
                  Select-Object -First 1
        if (-not $policy) {
            $script:Issues.Add("No machine policy retrieved from MP")
            Write-Log "No machine policy retrieved from MP" -Severity Warning
            return $false
        }
        return $true
    } catch {
        $script:Issues.Add("Policy WMI query failed: $($_.Exception.Message)")
        return $false
    }
}

function Test-MPConnectivity {
    Write-Log "Checking management point connectivity..."
    try {
        $sms = Get-CimInstance -Namespace 'root\ccm' -ClassName SMS_Authority -ErrorAction Stop
        if ($sms) {
            $mp = $sms.CurrentManagementPoint
            Write-Log "Current MP: $mp"
            if ([string]::IsNullOrWhiteSpace($mp)) {
                $script:Issues.Add("No current management point assigned")
                return $false
            }
            # TCP test on 80/443
            $ok = Test-NetConnection -ComputerName $mp -Port 443 -InformationLevel Quiet -WarningAction SilentlyContinue
            if (-not $ok) {
                $ok = Test-NetConnection -ComputerName $mp -Port 80 -InformationLevel Quiet -WarningAction SilentlyContinue
            }
            if (-not $ok) {
                $script:Issues.Add("Cannot reach MP $mp on 80/443")
                Write-Log "Cannot reach MP $mp on 80/443" -Severity Error
                return $false
            }
            return $true
        }
    } catch {
        $script:Issues.Add("SMS_Authority query failed: $($_.Exception.Message)")
        Write-Log "SMS_Authority query failed: $($_.Exception.Message)" -Severity Error
        return $false
    }
    return $false
}

#endregion

#region ---------- Remediation ----------

function Repair-Services {
    param([string[]]$Services)
    foreach ($name in $Services) {
        try {
            $svc = Get-Service -Name $name -ErrorAction Stop
            if ($svc.StartType -eq 'Disabled') {
                Set-Service -Name $name -StartupType Automatic
                Write-Log "Re-enabled disabled service: $name"
            }
            if ($svc.Status -ne 'Running') {
                Start-Service -Name $name -ErrorAction Stop
                Write-Log "Started service: $name"
                $script:Actions.Add("Started service $name")
            }
        } catch {
            Write-Log "Failed to start ${name}: $($_.Exception.Message)" -Severity Error
        }
    }
}

function Repair-ClientCache {
    Write-Log "Purging client cache..."
    try {
        $cm = New-Object -ComObject 'UIResource.UIResourceMgr'
        $cache = $cm.GetCacheInfo()
        $cache.GetCacheElements() | ForEach-Object {
            try {
                $cache.DeleteCacheElement($_.CacheElementID)
            } catch {
                Write-Log "Could not delete cache element $($_.CacheElementID)" -Severity Warning
            }
        }
        Write-Log "Cache purged"
        $script:Actions.Add("Purged ccmcache")
    } catch {
        Write-Log "Cache purge failed: $($_.Exception.Message)" -Severity Error
    }
}

function Invoke-ClientAction {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$ScheduleId, [string]$Description)

    try {
        $null = Invoke-CimMethod -Namespace 'root\ccm' -ClassName SMS_Client `
                                 -MethodName TriggerSchedule `
                                 -Arguments @{ sScheduleID = $ScheduleId } -ErrorAction Stop
        Write-Log "Triggered: $Description ($ScheduleId)"
        $script:Actions.Add("Triggered $Description")
    } catch {
        Write-Log "Failed to trigger ${Description}: $($_.Exception.Message)" -Severity Warning
    }
}

function Invoke-AllClientActions {
    Write-Log "Triggering standard ConfigMgr client actions..."
    $actions = @{
        '{00000000-0000-0000-0000-000000000021}' = 'Machine Policy Retrieval'
        '{00000000-0000-0000-0000-000000000022}' = 'Machine Policy Evaluation'
        '{00000000-0000-0000-0000-000000000001}' = 'Hardware Inventory'
        '{00000000-0000-0000-0000-000000000002}' = 'Software Inventory'
        '{00000000-0000-0000-0000-000000000113}' = 'Software Update Scan'
        '{00000000-0000-0000-0000-000000000114}' = 'Software Update Deployment Evaluation'
        '{00000000-0000-0000-0000-000000000121}' = 'Application Deployment Evaluation'
        '{00000000-0000-0000-0000-000000000003}' = 'Discovery Data Collection'
    }
    foreach ($k in $actions.Keys) {
        Invoke-ClientAction -ScheduleId $k -Description $actions[$k]
        Start-Sleep -Seconds 2
    }
}

function Repair-CMClient {
    Write-Log "Initiating CCM client repair (ccmrepair.exe)..." -Severity Warning
    $ccmRepair = Join-Path $env:WinDir 'CCM\ccmrepair.exe'
    if (-not (Test-Path $ccmRepair)) {
        # Fallback: invoke via WMI
        try {
            $null = Invoke-CimMethod -Namespace 'root\ccm' -ClassName SMS_Client -MethodName RepairClient -ErrorAction Stop
            Write-Log "RepairClient WMI method invoked"
            $script:Actions.Add("Invoked SMS_Client::RepairClient")
            return
        } catch {
            Write-Log "RepairClient WMI invocation failed: $($_.Exception.Message)" -Severity Error
            return
        }
    }
    try {
        Start-Process -FilePath $ccmRepair -WindowStyle Hidden
        Write-Log "ccmrepair.exe launched"
        $script:Actions.Add("Launched ccmrepair.exe")
    } catch {
        Write-Log "ccmrepair.exe failed: $($_.Exception.Message)" -Severity Error
    }
}

function Repair-SoftwareCenterShortcut {
    Write-Log "Reregistering Software Center..."
    try {
        $sc = "$env:WinDir\CCM\ClientUX\SCClient.exe"
        if (Test-Path $sc) {
            Start-Process -FilePath $sc -ArgumentList '-uninstall' -Wait -WindowStyle Hidden -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 2
            Start-Process -FilePath $sc -WindowStyle Hidden -ErrorAction SilentlyContinue
            Write-Log "SCClient re-registered"
            $script:Actions.Add("Re-registered SCClient")
        }
    } catch {
        Write-Log "SCClient re-register failed: $($_.Exception.Message)" -Severity Warning
    }
}

#endregion

#region ---------- Main ----------

Write-Log "==================== SCCM Health Check Started ===================="
Write-Log "Computer: $env:COMPUTERNAME | User context: $(whoami)"
Write-Log "Parameters: SkipRepair=$SkipRepair  ForceRepair=$ForceRepair  MaxCacheSizeMB=$MaxCacheSizeMB"

if (-not (Test-Admin)) {
    Write-Log "Not running elevated. Exiting." -Severity Error
    exit 1
}

if (-not (Test-CMClientInstalled)) {
    Write-Log "ConfigMgr client is NOT installed on this device." -Severity Error
    $script:Issues.Add("CM client not installed")
    exit 1
}

# --- Run all detections ---
$badServices    = Test-RequiredServices
$wmiOk          = Test-WMIHealth
$cacheOk        = Test-ClientCache
$shortcutOk     = Test-SoftwareCenterShortcut
$policyOk       = Test-ClientPolicy
$mpOk           = Test-MPConnectivity

Write-Log "------ Detection Summary ------"
Write-Log ("Issues found : {0}" -f $script:Issues.Count)
$script:Issues | ForEach-Object { Write-Log "  - $_" -Severity Warning }

if ($SkipRepair) {
    Write-Log "SkipRepair specified - exiting without remediation."
    if ($script:Issues.Count -gt 0) { exit 1 } else { exit 0 }
}

# --- Remediation ---
Write-Log "------ Remediation ------"

if ($badServices.Count -gt 0) { Repair-Services -Services $badServices }

if (-not $cacheOk)    { Repair-ClientCache }
if (-not $shortcutOk) { Repair-SoftwareCenterShortcut }

# Hard-failure scenarios trigger full repair
$needsFullRepair = $ForceRepair -or (-not $wmiOk) -or (-not $policyOk -and -not $mpOk)

if ($needsFullRepair) {
    Repair-CMClient
    Write-Log "Waiting 60s for client repair to start..."
    Start-Sleep -Seconds 60
}

# Always re-trigger client actions after remediation
if ($wmiOk -or $needsFullRepair) {
    Invoke-AllClientActions
}

Write-Log "------ Actions Taken ------"
if ($script:Actions.Count -eq 0) {
    Write-Log "No remediation actions were necessary."
} else {
    $script:Actions | ForEach-Object { Write-Log "  + $_" }
}

Write-Log "==================== SCCM Health Check Finished ===================="

# Exit code reflects health after remediation
if ($script:Issues.Count -gt 0 -and $script:Actions.Count -eq 0) {
    exit 1
} else {
    exit 0
}

#endregion
